title: Lead Web
description: Lead project website
baseurl: ""
url: "https://jmangold23.github.io/lead-web"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag