title: Lead Web
description: Lead project website
baseurl: ""
url: "https://lead.dwellingdb.com"

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Include CNAME file in build
include:
  - CNAME