name = "lead-storage-api"
main = "worker.js"
compatibility_date = "2024-08-28"

[env.production]
# For Cloudflare R2 (recommended - S3-compatible)
[[env.production.r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "lead-storage"

# For KV storage (alternative)
[[env.production.kv_namespaces]]
binding = "LEADS_KV"
id = "your-kv-namespace-id"

# Environment variables
[env.production.vars]
ALLOWED_ORIGIN = "https://lead.dwellingdb.com"
# S3_ENDPOINT = "https://s3.amazonaws.com"
# S3_BUCKET = "your-bucket-name"
# Add S3_ACCESS_KEY and S3_SECRET_KEY via wrangler secret

# Routes
[[env.production.routes]]
pattern = "api.lead.dwellingdb.com/*"
zone_name = "dwellingdb.com"

# Or use a subdomain route
# [[env.production.routes]]
# pattern = "lead.dwellingdb.com/api/*"
# zone_name = "dwellingdb.com"